#!/usr/bin/with-contenv bashio
set -euo pipefail

export DISCORD_TOKEN="$(bashio::config 'discord_token')"
export DISCORD_CLIENT_ID="$(bashio::config 'discord_client_id')"
export DISCORD_GUILD_ID="$(bashio::config 'discord_guild_id')"
export BOT_ALLOWED_CHANNEL_IDS="$(bashio::config 'bot_allowed_channel_ids')"
export BOT_ADMIN_ROLE_IDS="$(bashio::config 'bot_admin_role_ids')"
export BOT_PERSONA_STYLE="$(bashio::config 'bot_persona_style')"
export BOT_PERSONA_FILE="$(bashio::config 'bot_persona_file')"

export SHOLOM_ENABLED="$(bashio::config 'sholom_enabled')"
export SHOLOM_TRIGGER="$(bashio::config 'sholom_trigger')"
export SHOLOM_AUDIO_PATH="$(bashio::config 'sholom_audio_path')"
export SHOLOM_COOLDOWN_SECONDS="$(bashio::config 'sholom_cooldown_seconds')"
export SHOLOM_LEAVE_AFTER_SECONDS="$(bashio::config 'sholom_leave_after_seconds')"
export SHOLOM_RANDOM_ENABLED="$(bashio::config 'sholom_random_enabled')"
export SHOLOM_RANDOM_MIN_MINUTES="$(bashio::config 'sholom_random_min_minutes')"
export SHOLOM_RANDOM_MAX_MINUTES="$(bashio::config 'sholom_random_max_minutes')"

export GEMINI_API_KEY="$(bashio::config 'gemini_api_key')"
export GEMINI_MODEL="$(bashio::config 'gemini_model')"

export MC_SERVER_NAME="$(bashio::config 'mc_server_name')"
export MC_RCON_HOST="$(bashio::config 'mc_rcon_host')"
export MC_RCON_PORT="$(bashio::config 'mc_rcon_port')"
export MC_RCON_PASSWORD="$(bashio::config 'mc_rcon_password')"
export MC_QUERY_HOST="$(bashio::config 'mc_query_host')"
export MC_QUERY_PORT="$(bashio::config 'mc_query_port')"
export MC_LOG_PATH="$(bashio::config 'mc_log_path')"
export STATUS_LOG_LINES="$(bashio::config 'status_log_lines')"

export MEMORY_ENABLED="$(bashio::config 'memory_enabled')"
export MEMORY_PATH="$(bashio::config 'memory_path')"
export MAX_MEMORY_ITEMS="$(bashio::config 'max_memory_items')"
export MAX_MEMORY_ENTRY_LENGTH="$(bashio::config 'max_memory_entry_length')"
export CONVERSATION_MEMORY_ENABLED="$(bashio::config 'conversation_memory_enabled')"
export CONVERSATION_MEMORY_PATH="$(bashio::config 'conversation_memory_path')"
export CONVERSATION_MEMORY_MAX_TURNS="$(bashio::config 'conversation_memory_max_turns')"
export CONVERSATION_MEMORY_RECENT_TURNS="$(bashio::config 'conversation_memory_recent_turns')"
export CONVERSATION_MEMORY_RELEVANT_TURNS="$(bashio::config 'conversation_memory_relevant_turns')"
export CONVERSATION_MEMORY_MAX_ENTRY_LENGTH="$(bashio::config 'conversation_memory_max_entry_length')"
export CONVERSATION_MEMORY_MAX_PROMPT_CHARS="$(bashio::config 'conversation_memory_max_prompt_chars')"
export CHAT_OBSERVE_ENABLED="$(bashio::config 'chat_observe_enabled')"
export CHAT_OBSERVE_MIN_MESSAGE_LENGTH="$(bashio::config 'chat_observe_min_message_length')"
export CHAT_CHIME_ENABLED="$(bashio::config 'chat_chime_enabled')"
export CHAT_CHIME_PROBABILITY="$(bashio::config 'chat_chime_probability')"
export CHAT_CHIME_COOLDOWN_MINUTES="$(bashio::config 'chat_chime_cooldown_minutes')"
export CHAT_CHIME_MIN_MESSAGE_LENGTH="$(bashio::config 'chat_chime_min_message_length')"
export CHAT_REVIVE_ENABLED="$(bashio::config 'chat_revive_enabled')"
export CHAT_REVIVE_CHANNEL_ID="$(bashio::config 'chat_revive_channel_id')"
export CHAT_REVIVE_IDLE_MINUTES="$(bashio::config 'chat_revive_idle_minutes')"
export CHAT_REVIVE_COOLDOWN_MINUTES="$(bashio::config 'chat_revive_cooldown_minutes')"
export CHAT_REVIVE_CHECK_INTERVAL_MINUTES="$(bashio::config 'chat_revive_check_interval_minutes')"
export CHAT_REVIVE_USE_EVERYONE="$(bashio::config 'chat_revive_use_everyone')"
export CHAT_REVIVE_MESSAGE="$(bashio::config 'chat_revive_message')"

export VISION_ENABLED="$(bashio::config 'vision_enabled')"
export MAX_IMAGE_BYTES="$(bashio::config 'max_image_bytes')"
export MAX_VIDEO_BYTES="$(bashio::config 'max_video_bytes')"

export SNITCHING_ENABLED="$(bashio::config 'snitching_enabled')"
export SNITCH_CHANNEL_ID="$(bashio::config 'snitch_channel_id')"
export SNITCH_ALLOW_USER_REPORTS="$(bashio::config 'snitch_allow_user_reports')"
export SNITCH_REPORT_MODERATION_EVENTS="$(bashio::config 'snitch_report_moderation_events')"
export SNITCH_AUTO_PUNISH_ENABLED="$(bashio::config 'snitch_auto_punish_enabled')"
export SNITCH_MIN_TIMEOUT_MINUTES="$(bashio::config 'snitch_min_timeout_minutes')"
export SNITCH_TIMEOUT_MINUTES="$(bashio::config 'snitch_timeout_minutes')"
export SNITCH_MAX_TIMEOUT_MINUTES="$(bashio::config 'snitch_max_timeout_minutes')"
export SNITCH_COOLDOWN_SECONDS="$(bashio::config 'snitch_cooldown_seconds')"
export SNITCH_ESCALATE_REPEAT_REPORTS="$(bashio::config 'snitch_escalate_repeat_reports')"
export SNITCH_REPEAT_LOOKBACK_DAYS="$(bashio::config 'snitch_repeat_lookback_days')"

export MODERATION_ENABLED="$(bashio::config 'moderation_enabled')"
export MODERATION_LOG_CHANNEL_ID="$(bashio::config 'moderation_log_channel_id')"
export MODERATION_MIN_TIMEOUT_MINUTES="$(bashio::config 'moderation_min_timeout_minutes')"
export MODERATION_MAX_TIMEOUT_MINUTES="$(bashio::config 'moderation_max_timeout_minutes')"
export MODERATION_RULE_TIMEOUT_MINUTES="$(bashio::config 'moderation_rule_timeout_minutes')"
export MODERATION_OFFENSE_TIMEOUT_MINUTES="$(bashio::config 'moderation_offense_timeout_minutes')"
export MODERATION_SPAM_TIMEOUT_MINUTES="$(bashio::config 'moderation_spam_timeout_minutes')"
export SPAM_BIBIAI_WINDOW_MS="$(bashio::config 'spam_bibiai_window_ms')"
export SPAM_BIBIAI_LIMIT="$(bashio::config 'spam_bibiai_limit')"

export EVENT_LOG_PATH="$(bashio::config 'event_log_path')"
export EVENT_LOG_RETENTION_DAYS="$(bashio::config 'event_log_retention_days')"
export EVENT_LOG_MAX_ITEMS="$(bashio::config 'event_log_max_items')"

export MC_MONITOR_ENABLED="$(bashio::config 'mc_monitor_enabled')"
export MC_MONITOR_INTERVAL_MINUTES="$(bashio::config 'mc_monitor_interval_minutes')"
export MC_RECOVERY_ENABLED="$(bashio::config 'mc_recovery_enabled')"
export MC_RECOVERY_WEBHOOK_URL="$(bashio::config 'mc_recovery_webhook_url')"
export MC_RECOVERY_WEBHOOK_METHOD="$(bashio::config 'mc_recovery_webhook_method')"
export MC_RECOVERY_OFFLINE_CHECKS="$(bashio::config 'mc_recovery_offline_checks')"
export PEBBLEHOST_API_ENABLED="$(bashio::config 'pebblehost_api_enabled')"
export PEBBLEHOST_API_TOKEN="$(bashio::config 'pebblehost_api_token')"
export PEBBLEHOST_SERVER_ID="$(bashio::config 'pebblehost_server_id')"
export PEBBLEHOST_RECOVERY_SIGNAL="$(bashio::config 'pebblehost_recovery_signal')"
export PEBBLEHOST_API_BASE_URL="$(bashio::config 'pebblehost_api_base_url')"

export JOIN_SERVER_ADDRESS="$(bashio::config 'join_server_address')"
export JOIN_MODPACK_NAME="$(bashio::config 'join_modpack_name')"
export JOIN_MODPACK_URL="$(bashio::config 'join_modpack_url')"
export JOIN_MODRINTH_MODPACK_URL="$(bashio::config 'join_modrinth_modpack_url')"
export JOIN_CURSEFORGE_MODPACK_URL="$(bashio::config 'join_curseforge_modpack_url')"
export JOIN_MODPACK_LOADER="$(bashio::config 'join_modpack_loader')"
export JOIN_MINECRAFT_VERSION="$(bashio::config 'join_minecraft_version')"
export JOIN_INSTALL_GUIDE_URL="$(bashio::config 'join_install_guide_url')"
export JOIN_HELP_CHANNEL_ID="$(bashio::config 'join_help_channel_id')"
export JOIN_EXTRA_NOTES="$(bashio::config 'join_extra_notes')"
export JOIN_AUTO_REPLY_ENABLED="$(bashio::config 'join_auto_reply_enabled')"

export VACATION_MODE_ENABLED="$(bashio::config 'vacation_mode_enabled')"
export VACATION_RETURN_DATE="$(bashio::config 'vacation_return_date')"
export VACATION_REPORT_CHANNEL_ID="$(bashio::config 'vacation_report_channel_id')"
export VACATION_DAILY_REPORT_ENABLED="$(bashio::config 'vacation_daily_report_enabled')"
export VACATION_REPORT_HOUR_UTC="$(bashio::config 'vacation_report_hour_utc')"
export VACATION_AUTO_REPLY_ENABLED="$(bashio::config 'vacation_auto_reply_enabled')"
export VACATION_OWNER_NOTE="$(bashio::config 'vacation_owner_note')"
export VACATION_RULES_SUMMARY="$(bashio::config 'vacation_rules_summary')"
export VACATION_FULL_MODERATION_ENABLED="$(bashio::config 'vacation_full_moderation_enabled')"
export VACATION_DELETE_RULEBREAKING_MESSAGES="$(bashio::config 'vacation_delete_rulebreaking_messages')"
export VACATION_TIMEOUT_LOW_MINUTES="$(bashio::config 'vacation_timeout_low_minutes')"
export VACATION_TIMEOUT_MEDIUM_MINUTES="$(bashio::config 'vacation_timeout_medium_minutes')"
export VACATION_TIMEOUT_HIGH_MINUTES="$(bashio::config 'vacation_timeout_high_minutes')"
export VACATION_TIMEOUT_CRITICAL_MINUTES="$(bashio::config 'vacation_timeout_critical_minutes')"
export VACATION_MAX_TIMEOUT_MINUTES="$(bashio::config 'vacation_max_timeout_minutes')"
export VACATION_ESCALATE_REPEAT_OFFENSES="$(bashio::config 'vacation_escalate_repeat_offenses')"
export VACATION_REPEAT_LOOKBACK_DAYS="$(bashio::config 'vacation_repeat_lookback_days')"
export VACATION_RAPID_SPAM_WINDOW_MS="$(bashio::config 'vacation_rapid_spam_window_ms')"
export VACATION_RAPID_SPAM_LIMIT="$(bashio::config 'vacation_rapid_spam_limit')"
export VACATION_DUPLICATE_SPAM_LIMIT="$(bashio::config 'vacation_duplicate_spam_limit')"
export VACATION_BLOCKED_TERMS="$(bashio::config 'vacation_blocked_terms')"

export MINECRAFT_REPORT_CHANNEL_ID="$(bashio::config 'minecraft_report_channel_id')"
export WEEKLY_REPORT_ENABLED="$(bashio::config 'weekly_report_enabled')"
export WEEKLY_REPORT_DAY="$(bashio::config 'weekly_report_day')"
export WEEKLY_REPORT_HOUR_UTC="$(bashio::config 'weekly_report_hour_utc')"

export AI_AUTO_EXECUTE_SAFE_COMMANDS="$(bashio::config 'ai_auto_execute_safe_commands')"
export ALLOW_STOP_COMMAND="$(bashio::config 'allow_stop_command')"
export BYPASS_RCON_SAFETY="$(bashio::config 'bypass_rcon_safety')"
export MAX_COMMANDS_PER_FIX="$(bashio::config 'max_commands_per_fix')"
export RCON_TIMEOUT_MS="$(bashio::config 'rcon_timeout_ms')"

if [[ -z "${DISCORD_TOKEN}" || -z "${DISCORD_CLIENT_ID}" || -z "${GEMINI_API_KEY}" || -z "${MC_RCON_PASSWORD}" ]]; then
  bashio::log.fatal "Missing required add-on options: discord_token, discord_client_id, gemini_api_key, or mc_rcon_password."
  exit 1
fi

cd /app
exec npm start
